name: Python type check
on: [push, pull_request]
jobs:
  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Lint with mypy
        run: pipx --python python3.14 run tox -e type

  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.14'
    - uses: pre-commit/action@v3.0.1
